apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-assignment-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: assignment-app
  template:
    metadata:
      labels:
        app: assignment-app
    spec:
      containers:
      - name: assignment-app
        image: shahchetali/scalable-services-assignment:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: scalable-assignment-service
spec:
  selector:
    app: scalable-assignment-deployment
  ports:
  - port: 6000
    targetPort: 5000
  type: LoadBalancer